### PR TITLE
fix: enable rtttl finished playback callback define

### LINKED ISSUE #627: Compile error with RATGDOOutput - missing member w/ESPH 2026.5.0
While building with ESPHome Device Builder 2026.5.0

```
Compiling .pioenvs/ratgdo32disco-garagedoor/src/esphome/components/ratgdo/lock/ratgdo_lock.cpp.o
Compiling .pioenvs/ratgdo32disco-garagedoor/src/esphome/components/ratgdo/number/ratgdo_number.cpp.o
Compiling .pioenvs/ratgdo32disco-garagedoor/src/esphome/components/ratgdo/observable.cpp.o
Compiling .pioenvs/ratgdo32disco-garagedoor/src/esphome/components/ratgdo/output/ratgdo_output.cpp.o
src/esphome/components/ratgdo/output/ratgdo_output.cpp: In member function 'virtual void esphome::ratgdo::RATGDOOutput::setup()':
src/esphome/components/ratgdo/output/ratgdo_output.cpp:14:24: error: 'class esphome::rtttl::Rtttl' has no member named 'add_on_finished_playback_callback'
   14 |         this->beeper_->add_on_finished_playback_callback([this] { this->finished_playback(); });
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compiling .pioenvs/ratgdo32disco-garagedoor/src/esphome/components/ratgdo/ratgdo.cpp.o
*** [.pioenvs/ratgdo32disco-garagedoor/src/esphome/components/ratgdo/output/ratgdo_output.cpp.o] Error 1
========================= [FAILED] Took 101.64 seconds =========================

```

This may be expected with the current esphome bits - not sure.

### PR DESCRIPTION
**Pull request by bluetoothbot**
## Summary

ESPHome 2026.5.0 gates `Rtttl::add_on_finished_playback_callback` behind the `USE_RTTTL_FINISHED_PLAYBACK_CALLBACK` define, which is normally set only when YAML configures `on_finished_playback:`. `RATGDOOutput::setup()` calls the method directly from C++, breaking the build on 2026.5.0. The fix adds the define from the ratgdo output component's `to_code()` whenever the beeper is configured.

Fixes https://github.com/ratgdo/esphome-ratgdo/issues/627

## Changes

- `components/ratgdo/output/__init__.py`: add `cg.add_define("USE_RTTTL_FINISHED_PLAYBACK_CALLBACK")` in `to_code()`.

## Test plan

- [ ] Verify a v32disco build (which uses the beeper output) compiles on ESPHome 2026.5.0.
- [ ] Confirm the `on_finished_playback` callback still fires so beeper song repeat continues to work.

---
*Generated by Kōan /fix*

---
### Quality Report

**Changes**: 1 file changed, 3 insertions(+)

**Code scan**: clean

**Tests**: passed (11 passed)

**Branch hygiene**: clean

*Generated by Kōan post-mission quality pipeline*

### CODE REVIEW

**Review by bdraco — CHANGES_REQUESTED** [review]
We should instead restructure so we aren't bypassing codegen and don't need to add the define. thats a bit of a hack

**Comment by bdraco** [comment]
@bluetoothbot rr

**Comment by bdraco** [comment]
> > @bdraco: @bluetoothbot rr
> 
> Re-reviewed. I agree this approach is a hack and should be restructured — leaving the inline review with the rationale.
> 
> The cleanest path is to drop the direct `rtttl_->add_on_finished_playback_callback(...)` call from `RATGDOOutput::setup()` and instead poll `rtttl_->is_playing()` in `loop()`, tracking a `was_playing_` edge to fire the song-repeat logic on the falling edge. That keeps the beeper-repeat behavior self-contained, removes the dependency on the `USE_RTTTL_FINISHED_PLAYBACK_CALLBACK` define entirely, and avoids touching the component's YAML surface.
> 
> If you'd rather keep callback semantics, the alternative is to add an optional `on_finished_playback` automation to the output component's schema and emit it through codegen against the parent rtttl variable — that makes upstream set the define for the right reason. Happy to take whichever direction you prefer; I'll abandon this PR and open a fresh one with the polling approach unless you say otherwise.

No, disagree, setup a real automation in the yaml so we don't have to have this hack

**Comment by bdraco** [comment]
@bluetoothbot rr

**Comment by bdraco** [comment]
almost .. but at least you found the problem

https://github.com/ratgdo/esphome-ratgdo/pull/629
