### PR TITLE
Trigger rtttl finished-playback callback from YAML automation

### LINKED ISSUE #627: Compile error with RATGDOOutput - missing member w/ESPH 2026.5.0
While building with ESPHome Device Builder 2026.5.0

```
Compiling .pioenvs/ratgdo32disco-garagedoor/src/esphome/components/ratgdo/lock/ratgdo_lock.cpp.o
Compiling .pioenvs/ratgdo32disco-garagedoor/src/esphome/components/ratgdo/number/ratgdo_number.cpp.o
Compiling .pioenvs/ratgdo32disco-garagedoor/src/esphome/components/ratgdo/observable.cpp.o
Compiling .pioenvs/ratgdo32disco-garagedoor/src/esphome/components/ratgdo/output/ratgdo_output.cpp.o
src/esphome/components/ratgdo/output/ratgdo_output.cpp: In member function 'virtual void esphome::ratgdo::RATGDOOutput::setup()':
src/esphome/components/ratgdo/output/ratgdo_output.cpp:14:24: error: 'class esphome::rtttl::Rtttl' has no member named 'add_on_finished_playback_callback'
   14 |         this->beeper_->add_on_finished_playback_callback([this] { this->finished_playback(); });
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Compiling .pioenvs/ratgdo32disco-garagedoor/src/esphome/components/ratgdo/ratgdo.cpp.o
*** [.pioenvs/ratgdo32disco-garagedoor/src/esphome/components/ratgdo/output/ratgdo_output.cpp.o] Error 1
========================= [FAILED] Took 101.64 seconds =========================

```

This may be expected with the current esphome bits - not sure.

### PR DESCRIPTION
**Pull request by bdraco**
## What

Register the rtttl finished-playback callback from YAML instead of from C++ in `RATGDOOutput::setup()`, restoring the v32 disco build on ESPHome 2026.5.0.

## Why

ESPHome 2026.5.0 gates `Rtttl::add_on_finished_playback_callback` behind `USE_RTTTL_FINISHED_PLAYBACK_CALLBACK`, and the rtttl component only sets that define when a `rtttl:` entry configures `on_finished_playback:`. `RATGDOOutput::setup()` was calling the method directly from C++, so the v32 disco beeper build now fails with `'class esphome::rtttl::Rtttl' has no member named 'add_on_finished_playback_callback'`.

## How

- Drop the `add_on_finished_playback_callback` registration from `RATGDOOutput::setup()`; the existing public `RATGDOOutput::finished_playback()` is now the entry point invoked from YAML.
- Add an `on_finished_playback:` automation to the rtttl entry in `v32disco.yaml`, `v32disco_secplusv1.yaml`, and `v32disco_drycontact.yaml`. The automation calls `id(${id_prefix}_beeper).finished_playback()` via lambda, which both flips the define on at compile time and routes completion events back into the existing repeat logic.

The C++ `finished_playback()` body still consults `repeat_`, which is still driven by the `subscribe_door_action_delayed` subscription in `setup()`, so beeper song repeat continues to work unchanged.

## Testing

- `pytest tests/` passes (11 passed).
- `pre-commit run` clean on the touched files.
- Unverified on hardware; needs the operator to flash a v32 disco board and confirm the door-action delay beeper sequence still repeats while the door is moving, and stops on completion.

Closes #627

### CODE REVIEW

**Comment by jdranchman** [comment]
Verified - build works now

Firmware Version	2026.5.0 (config hash 0xd27db7e8, built 2026-05-22 11:34:12 -0600)

Thanks for a very fast fix!

**Comment by bdraco** [comment]
Thanks for confirming. Helps the bot found the problem quickly. That was most of the work
