### ISSUE TITLE
Build Failure (ESP8266): 'class esphome::Application' has no member named 'wake_loop_threadsafe' in ESPHome 2026.2.4

### ISSUE THREAD

**Issue by freeblazin** [ratgdo/esphome-ratgdo#616]
### Description
Attempting to compile the `main` branch against ESPHome 2026.2.4 on an ESP8266 board results in a fatal compiler error. The recent ESPHome core architectural changes to the `wake_loop` function break the current calls in `ratgdo_uart_esp8266.h`.

### Hardware
* RATGDO v2.0 (ESP8266 / d1_mini)
* ESPHome version: 2026.2.4

### Logs / Compiler Output
```text
In file included from src/esphome/components/ratgdo/ratgdo_uart.h:8,
                 from src/esphome/components/ratgdo/ratgdo_uart_esp32.cpp:1:
src/esphome/components/ratgdo/ratgdo_uart_esp8266.h: In function 'void esphome::ratgdo::ratgdo_wake_main_loop_from_isr()':
src/esphome/components/ratgdo/ratgdo_uart_esp8266.h:15:62: error: 'class esphome::Application' has no member named 'wake_loop_threadsafe'
   15 | inline void IRAM_ATTR ratgdo_wake_main_loop_from_isr() { App.wake_loop_threadsafe(); }
      |                                                              ^~~~~~~~~~~~~~~~~~~~
```

### Steps to Reproduce

* Include the remote package pointing to @main
* Compile using ESPHome 2026.2.4 targeting an esp8266 board (d1_mini).
* Build fails on ratgdo_uart_esp8266.h.

**Comment by PaulWieland** [comment]
The automated build process is completing without issue using 2026.4.2

**Comment by freeblazin** [comment]
Ah, I should have tested against the latest version.  2026.4.3 compiles successfully.

I appreciate you and the supporting devs for all the hard work creating and maintaining this project! Looking forward to receiving the latest version of the hardware for my recent order.
